# Importing libraries

In [1]:
import pandas as pd
import numpy as np

# import the data from excel (from csv file)

In [97]:
salesdata = pd.DataFrame(pd.read_csv(r'Video_Games_Sales_as_at_22_Dec_2016.csv')) #pd.DataFrame isn't necessary
salesdata

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning the dataset

In [98]:

#for col in salesdata.columns: print(col,end ="-"), print(salesdata[col].isnull().str.count('True'))

#for col in salesdata.columns:
#    print(salesdata[col].isna())
    
#for col in salesdata.columns:print(col," : ",len(salesdata[salesdata[col].isna()][col]))

a = list([print(col," : ",len(salesdata[salesdata[col].isna()][col])) for col in salesdata.columns])

salesdata.dtypes

Name  :  2
Platform  :  0
Year_of_Release  :  269
Genre  :  2
Publisher  :  54
NA_Sales  :  0
EU_Sales  :  0
JP_Sales  :  0
Other_Sales  :  0
Global_Sales  :  0
Critic_Score  :  8582
Critic_Count  :  8582
User_Score  :  6704
User_Count  :  9129
Developer  :  6623
Rating  :  6769

Name                object
Platform            object
Year_of_Release    float64
Genre               object
Publisher           object
NA_Sales           float64
EU_Sales           float64
JP_Sales           float64
Other_Sales        float64
Global_Sales       float64
Critic_Score       float64
Critic_Count       float64
User_Score          object
User_Count         float64
Developer           object
Rating              object
dtype: object

In [100]:
salesdata = salesdata.applymap(str)
salesdata
salesdata.dtypes

Name               object
Platform           object
Year_of_Release    object
Genre              object
Publisher          object
NA_Sales           object
EU_Sales           object
JP_Sales           object
Other_Sales        object
Global_Sales       object
Critic_Score       object
Critic_Count       object
User_Score         object
User_Count         object
Developer          object
Rating             object
dtype: object